---
title: "Cleaning_Employment"
author: "Cynthia Ng"
date: "2022-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up
```{r}
# Load packages
library('tidyverse')
library('ggplot2')
library('rstudioapi')

# Set directory to data folder
cur_dir <- dirname(getSourceEditorContext()$path)
getwd()
setwd(cur_dir)
setwd("../data")
getwd()

# Read csv
df <- read_csv('raw_wf_demo.csv')
```

## Clean
```{r}
# 1. rcid column
# Remove since we don't need company id for only 6 companies
df <- subset(df, select = -c(rcid))

# 2. company column
# Remove ', Inc.' 
df$company <- gsub(
    pattern = (', Inc.'), 
    replacement = '',
    as.character(df$company))

# Remove '\\' 
df$company <- gsub(
  pattern = ('\\\\'), 
  replacement = '',
  as.character(df$company))

# Simplify company names for better readability
df$company[df$company=="The Home Depot"]<-"Home Depot"
df$company[df$company=="Bristol Myers Squibb Co."]<-"Bristol Myers Squibb"
df$company[df$company=="Accenture Plc"]<-"Accenture"
df$company[df$company=="The Goldman Sachs Group"]<-"Goldman Sachs"


# 3. region column
# Fill empty values with NA
df$region <- gsub(
  pattern = ('empty'), 
  replacement = NA,
  as.character(df$region))

# 4. year column
# change 'month' column to 'year'
df$year = substr(df$month,1,nchar(df$month)-3)
df <- subset(df, select = -c(month))
```

## Only include certain parts of the data
```{r}
# Set year as 2020
df <- subset(df, year == 2020)

# Set region as Northern America
df <- subset(df, region=='Northern America')

# Remove the year and region columns since they're all the same
df <- subset(df, select = -c(year, region))

# Confirm that number of rows is the same
nrow(df)
```

## Impute Nas
```{r}
# Check which columns have NAs
which(colSums(is.na(df))>0)

# It looks like the "salary" column is the only one that has NAs 
# To deal with these NAs, let's impute salary values with the median value in the gender column
# Load plyr library 
library(plyr)

# Use ddply to impute
df <- ddply(df, 
      .(ethnicity), 
      transform, 
      salary=ifelse(is.na(salary), median(salary, na.rm=TRUE), salary))

# Confirm that there are no more NA values
which(colSums(is.na(df))>0)

# Confirm that number of rows is the same
nrow(df)
```

## Save data
```{r}
## SAVE FULL DF
cur_dir <- dirname(getSourceEditorContext()$path)
setwd(cur_dir)
setwd("../data")
write.csv(df, "cleaned_wf_demo.csv")

# Save sample df
# Upload sample dataframe to website
df_sam <- df[sample(nrow(df), 500), ]
write.csv(df_sam, "cleaned_wf_demo_sample.csv")
```